require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe QualificationAllowancesController do

  # This should return the minimal set of attributes required to create a valid
  # QualificationAllowance. As you add validations to QualificationAllowance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # QualificationAllowancesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all qualification_allowances as @qualification_allowances" do
      qualification_allowance = QualificationAllowance.create! valid_attributes
      get :index, {}, valid_session
      assigns(:qualification_allowances).should eq([qualification_allowance])
    end
  end

  describe "GET show" do
    it "assigns the requested qualification_allowance as @qualification_allowance" do
      qualification_allowance = QualificationAllowance.create! valid_attributes
      get :show, {:id => qualification_allowance.to_param}, valid_session
      assigns(:qualification_allowance).should eq(qualification_allowance)
    end
  end

  describe "GET new" do
    it "assigns a new qualification_allowance as @qualification_allowance" do
      get :new, {}, valid_session
      assigns(:qualification_allowance).should be_a_new(QualificationAllowance)
    end
  end

  describe "GET edit" do
    it "assigns the requested qualification_allowance as @qualification_allowance" do
      qualification_allowance = QualificationAllowance.create! valid_attributes
      get :edit, {:id => qualification_allowance.to_param}, valid_session
      assigns(:qualification_allowance).should eq(qualification_allowance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new QualificationAllowance" do
        expect {
          post :create, {:qualification_allowance => valid_attributes}, valid_session
        }.to change(QualificationAllowance, :count).by(1)
      end

      it "assigns a newly created qualification_allowance as @qualification_allowance" do
        post :create, {:qualification_allowance => valid_attributes}, valid_session
        assigns(:qualification_allowance).should be_a(QualificationAllowance)
        assigns(:qualification_allowance).should be_persisted
      end

      it "redirects to the created qualification_allowance" do
        post :create, {:qualification_allowance => valid_attributes}, valid_session
        response.should redirect_to(QualificationAllowance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved qualification_allowance as @qualification_allowance" do
        # Trigger the behavior that occurs when invalid params are submitted
        QualificationAllowance.any_instance.stub(:save).and_return(false)
        post :create, {:qualification_allowance => { "user_id" => "invalid value" }}, valid_session
        assigns(:qualification_allowance).should be_a_new(QualificationAllowance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        QualificationAllowance.any_instance.stub(:save).and_return(false)
        post :create, {:qualification_allowance => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested qualification_allowance" do
        qualification_allowance = QualificationAllowance.create! valid_attributes
        # Assuming there are no other qualification_allowances in the database, this
        # specifies that the QualificationAllowance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        QualificationAllowance.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => qualification_allowance.to_param, :qualification_allowance => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested qualification_allowance as @qualification_allowance" do
        qualification_allowance = QualificationAllowance.create! valid_attributes
        put :update, {:id => qualification_allowance.to_param, :qualification_allowance => valid_attributes}, valid_session
        assigns(:qualification_allowance).should eq(qualification_allowance)
      end

      it "redirects to the qualification_allowance" do
        qualification_allowance = QualificationAllowance.create! valid_attributes
        put :update, {:id => qualification_allowance.to_param, :qualification_allowance => valid_attributes}, valid_session
        response.should redirect_to(qualification_allowance)
      end
    end

    describe "with invalid params" do
      it "assigns the qualification_allowance as @qualification_allowance" do
        qualification_allowance = QualificationAllowance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QualificationAllowance.any_instance.stub(:save).and_return(false)
        put :update, {:id => qualification_allowance.to_param, :qualification_allowance => { "user_id" => "invalid value" }}, valid_session
        assigns(:qualification_allowance).should eq(qualification_allowance)
      end

      it "re-renders the 'edit' template" do
        qualification_allowance = QualificationAllowance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        QualificationAllowance.any_instance.stub(:save).and_return(false)
        put :update, {:id => qualification_allowance.to_param, :qualification_allowance => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested qualification_allowance" do
      qualification_allowance = QualificationAllowance.create! valid_attributes
      expect {
        delete :destroy, {:id => qualification_allowance.to_param}, valid_session
      }.to change(QualificationAllowance, :count).by(-1)
    end

    it "redirects to the qualification_allowances list" do
      qualification_allowance = QualificationAllowance.create! valid_attributes
      delete :destroy, {:id => qualification_allowance.to_param}, valid_session
      response.should redirect_to(qualification_allowances_url)
    end
  end

end
