require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SummaryAttendancesController do

  # This should return the minimal set of attributes required to create a valid
  # SummaryAttendance. As you add validations to SummaryAttendance, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "user_id" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SummaryAttendancesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all summary_attendances as @summary_attendances" do
      summary_attendance = SummaryAttendance.create! valid_attributes
      get :index, {}, valid_session
      assigns(:summary_attendances).should eq([summary_attendance])
    end
  end

  describe "GET show" do
    it "assigns the requested summary_attendance as @summary_attendance" do
      summary_attendance = SummaryAttendance.create! valid_attributes
      get :show, {:id => summary_attendance.to_param}, valid_session
      assigns(:summary_attendance).should eq(summary_attendance)
    end
  end

  describe "GET new" do
    it "assigns a new summary_attendance as @summary_attendance" do
      get :new, {}, valid_session
      assigns(:summary_attendance).should be_a_new(SummaryAttendance)
    end
  end

  describe "GET edit" do
    it "assigns the requested summary_attendance as @summary_attendance" do
      summary_attendance = SummaryAttendance.create! valid_attributes
      get :edit, {:id => summary_attendance.to_param}, valid_session
      assigns(:summary_attendance).should eq(summary_attendance)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SummaryAttendance" do
        expect {
          post :create, {:summary_attendance => valid_attributes}, valid_session
        }.to change(SummaryAttendance, :count).by(1)
      end

      it "assigns a newly created summary_attendance as @summary_attendance" do
        post :create, {:summary_attendance => valid_attributes}, valid_session
        assigns(:summary_attendance).should be_a(SummaryAttendance)
        assigns(:summary_attendance).should be_persisted
      end

      it "redirects to the created summary_attendance" do
        post :create, {:summary_attendance => valid_attributes}, valid_session
        response.should redirect_to(SummaryAttendance.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved summary_attendance as @summary_attendance" do
        # Trigger the behavior that occurs when invalid params are submitted
        SummaryAttendance.any_instance.stub(:save).and_return(false)
        post :create, {:summary_attendance => { "user_id" => "invalid value" }}, valid_session
        assigns(:summary_attendance).should be_a_new(SummaryAttendance)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SummaryAttendance.any_instance.stub(:save).and_return(false)
        post :create, {:summary_attendance => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested summary_attendance" do
        summary_attendance = SummaryAttendance.create! valid_attributes
        # Assuming there are no other summary_attendances in the database, this
        # specifies that the SummaryAttendance created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SummaryAttendance.any_instance.should_receive(:update).with({ "user_id" => "1" })
        put :update, {:id => summary_attendance.to_param, :summary_attendance => { "user_id" => "1" }}, valid_session
      end

      it "assigns the requested summary_attendance as @summary_attendance" do
        summary_attendance = SummaryAttendance.create! valid_attributes
        put :update, {:id => summary_attendance.to_param, :summary_attendance => valid_attributes}, valid_session
        assigns(:summary_attendance).should eq(summary_attendance)
      end

      it "redirects to the summary_attendance" do
        summary_attendance = SummaryAttendance.create! valid_attributes
        put :update, {:id => summary_attendance.to_param, :summary_attendance => valid_attributes}, valid_session
        response.should redirect_to(summary_attendance)
      end
    end

    describe "with invalid params" do
      it "assigns the summary_attendance as @summary_attendance" do
        summary_attendance = SummaryAttendance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SummaryAttendance.any_instance.stub(:save).and_return(false)
        put :update, {:id => summary_attendance.to_param, :summary_attendance => { "user_id" => "invalid value" }}, valid_session
        assigns(:summary_attendance).should eq(summary_attendance)
      end

      it "re-renders the 'edit' template" do
        summary_attendance = SummaryAttendance.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SummaryAttendance.any_instance.stub(:save).and_return(false)
        put :update, {:id => summary_attendance.to_param, :summary_attendance => { "user_id" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested summary_attendance" do
      summary_attendance = SummaryAttendance.create! valid_attributes
      expect {
        delete :destroy, {:id => summary_attendance.to_param}, valid_session
      }.to change(SummaryAttendance, :count).by(-1)
    end

    it "redirects to the summary_attendances list" do
      summary_attendance = SummaryAttendance.create! valid_attributes
      delete :destroy, {:id => summary_attendance.to_param}, valid_session
      response.should redirect_to(summary_attendances_url)
    end
  end

end
